#cluster:
#  mkdir -p logs/ &&
#  sbatch
#    --cpus-per-task={threads}
#    --mem={resources.mem_mb}
#    --output=logs/%j.out
#default-resources:
#  - mem_mb=1000
#  - runtime=70
jobs: 500

# go on with independent jobs if a job fails
keep-going: False

#rerun-incomplete: True
printshellcmds: True
cores: 96
groups:
  - optimize_network=groupjob
group-components:
  - groupjob=11
#max-jobs-per-second: 25

#retries: 3
#show-failed-logs: True
#cluster-cancel: scancel
# jobname
