cluster:
  mkdir -p logs/ &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --output=logs/%j.out
default-resources:
  - mem_mb=1000
  - runtime=180
jobs: 500

# go on with independent jobs if a job fails
keep-going: False

#rerun-incomplete: True
printshellcmds: True
cores: 96
groups:
  - optimize_network=groupjob
group-components:
  - groupjob=11
max-jobs-per-second: 25

#retries: 3
#show-failed-logs: True
#cluster-cancel: scancel

resources:
    # see comment in Snakefile
    cdsapi=1

config:
    # temp folder used for file API to solvers, used for cplex this path is passed to linopy if the
    # parameter io_api is not set to 'direct', i.e. lp/mps files are written to disk in order to
    # pass the model to the solver.
    # TODO there is a weird issue on the VSC, /tmp is out of space for larger runs, maybe disk is
    # not freed after the files have been deleted because they are still open? use /local as
    # workaround here if you get out-of-disk-space errors.
    solver_dir="/local"
