name: syfop-global-costs
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.5
  - aiohttp-retry=2.8.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - amply=0.1.6
  - amqp=5.1.1
  - ansiwrap=0.8.4
  - antlr-python-runtime=4.9.3
  - anyio=3.6.2
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=0.2.post
  - asttokens=2.2.1
  - async-timeout=4.0.3
  - asyncssh=2.13.2
  - atlite=0.2.9
  - atpublic=3.0.1
  - attmap=0.13.2
  - attr=2.5.1
  - attrs=22.2.0
  - autopep8=2.0.4
  - aws-c-common=0.8.14
  - aws-c-compression=0.2.16
  - aws-c-sdkutils=0.1.8
  - aws-checksums=0.1.14
  - aws-sdk-cpp=1.7.164
  - backcall=0.2.0
  - backoff=1.11.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.zoneinfo=0.2.1
  - bcrypt=4.0.1
  - beautifulsoup4=4.12.0
  - billiard=4.1.0
  - black=23.7.0
  - bleach=6.0.0
  - blosc=1.21.3
  - bokeh=2.4.3
  - boost-cpp=1.74.0
  - boto3=1.28.49
  - botocore=1.31.49
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.3.1
  - cairo=1.16.0
  - cartopy=0.20.2
  - cdsapi=0.6.1
  - celery=5.3.1
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=4.0.0
  - cftime=1.6.2
  - charset-normalizer=3.1.0
  - click=8.1.3
  - click-didyoumean=0.3.0
  - click-plugins=1.1.1
  - click-repl=0.2.0
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.8
  - coin-or-utils=2.11.9
  - coincbc=2.10.10
  - colorama=0.4.6
  - comm=0.1.3
  - configargparse=1.7
  - configobj=5.0.8
  - connection_pool=0.0.3
  - contourpy=1.0.7
  - cryptography=39.0.0
  - curl=7.86.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.3.0
  - dask-core=2023.3.0
  - datrie=0.8.2
  - dbus=1.13.6
  - debuglater=1.4.4
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - dictdiffer=0.9.0
  - diskcache=5.6.1
  - distributed=2023.3.0
  - distro=1.8.0
  - docutils=0.20.1
  - dpath=2.1.6
  - dropbox=11.36.2
  - dulwich=0.21.5
  - dvc=3.16.0
  - dvc-data=2.15.4
  - dvc-http=2.30.2
  - dvc-objects=1.0.1
  - dvc-render=0.5.3
  - dvc-studio-client=0.13.0
  - dvc-task=0.3.0
  - eido=0.2.1
  - entrypoints=0.4
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filechunkio=1.8
  - filelock=3.12.3
  - fiona=1.8.20
  - flatten-dict=0.4.2
  - flit-core=3.8.0
  - flufl.lock=7.1
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.3
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.4.0
  - fsspec=2023.3.0
  - ftputil=5.0.4
  - funcy=2.0
  - future=0.18.3
  - gdal=3.4.0
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.10.1
  - geotiff=1.7.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.32
  - glib=2.74.1
  - glib-tools=2.74.1
  - glog=0.6.0
  - google-api-core=2.11.1
  - google-api-python-client=2.99.0
  - google-auth=2.23.0
  - google-auth-httplib2=0.1.1
  - google-cloud-core=2.3.3
  - google-cloud-storage=2.10.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.6.0
  - googleapis-common-protos=1.60.0
  - grandalf=0.7
  - graphite2=1.3.13
  - greenlet=2.0.2
  - grpcio=1.46.3
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.5
  - gstreamer-orc=0.4.33
  - harfbuzz=3.1.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - httplib2=0.22.0
  - humanfriendly=10.0
  - humanize=4.8.0
  - hydra-core=1.3.2
  - icu=68.2
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.1.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipykernel=6.22.0
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - iterative-telemetry=0.0.8
  - jack=1.9.22
  - jedi=0.18.2
  - jemalloc=5.3.0
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.15
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.7
  - jupytext=1.15.1
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - kombu=5.3.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=11.1.0
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgdal=3.4.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgit2=1.5.1
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libjemalloc=5.3.0
  - libjpeg-turbo=2.1.4
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=13.5
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libtool=2.4.7
  - libudev1=253
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.9.2
  - libzlib=1.2.13
  - linopy=0.1.4
  - locket=1.0.0
  - logmuse=0.2.6
  - lz4=4.3.2
  - lz4-c=1.9.3
  - mapclassify=2.5.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.2
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.0
  - mistune=2.0.5
  - monotonic=1.5
  - mpg123=1.31.3
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nanotime=0.5.2
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert=7.2.10
  - nbconvert-core=7.2.10
  - nbconvert-pandoc=7.2.10
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf4=1.5.8
  - netgraph=4.12.11
  - networkx=3.0
  - nomkl=1.0
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89
  - numexpr=2.8.4
  - numpy=1.24.2
  - oauth2client=4.1.3
  - omegaconf=2.3.0
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - orc=1.8.3
  - orjson=3.9.5
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - papermill=2.4.0
  - paramiko=3.3.1
  - parquet-cpp=1.1.0
  - parso=0.8.3
  - partd=1.3.0
  - pathlib2=2.3.7.post1
  - pathspec=0.11.2
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.40
  - peppy=0.35.7
  - pexpect=4.8.0
  - pgeocode=0.4.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plac=1.3.5
  - platformdirs=3.2.0
  - ploomber=0.23.0
  - ploomber-core=0.2.14
  - ploomber-engine=0.0.31
  - ploomber-scaffold=0.3.1
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - poppler=21.11.0
  - poppler-data=0.4.12
  - postgresql=13.5
  - posthog=3.0.2
  - prettytable=3.9.0
  - progressbar2=4.2.0
  - proj=8.2.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=4.21.12
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydantic=1.10.12
  - pydot=1.2.4
  - pyflakes=3.1.0
  - pygit2=1.11.1
  - pygments=2.14.0
  - pygtrie=2.5.0
  - pynacl=1.5.0
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyproj=3.3.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.19.3
  - pysftp=0.2.9
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytest=7.2.2
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-gssapi=1.8.2
  - python-irodsclient=1.1.8
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python-utils=3.5.2
  - python_abi=3.9
  - pytz=2023.3
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt=5.12.9
  - qtconsole=5.4.1
  - qtconsole-base=5.4.1
  - qtpy=2.3.1
  - rasterio=1.2.10
  - re2=2023.02.02
  - readline=8.2
  - rectangle-packer=2.0.1
  - requests=2.28.2
  - reretry=0.11.8
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.5.1
  - rsa=4.9
  - rtree=1.0.1
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - s2n=1.3.33
  - s3transfer=0.6.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - scmrepo=1.3.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - setuptools=67.6.1
  - shapely=1.8.0
  - shortuuid=1.0.11
  - shtab=1.6.4
  - sip=6.7.7
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=6.4.0
  - smmap=3.0.5
  - snakemake=7.32.3
  - snakemake-minimal=7.32.3
  - snappy=1.1.10
  - sniffio=1.3.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=2.0.20
  - sqlite=3.40.0
  - sqlparse=0.4.4
  - sqltrie=0.7.0
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - stone=3.3.1
  - stopit=1.1.2
  - tabulate=0.9.0
  - tblib=1.7.0
  - tenacity=8.2.3
  - terminado=0.17.1
  - textwrap3=0.9.2
  - threadpoolctl=3.1.0
  - throttler=1.2.2
  - tiledb=2.5.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.1
  - toolz=0.12.0
  - toposort=1.10
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzcode=2023c
  - tzdata=2023c
  - ubiquerg=0.6.3
  - ucx=1.14.0
  - unicodedata2=15.0.0
  - uritemplate=4.1.1
  - urllib3=1.26.15
  - veracitools=0.1.3
  - vine=5.0.0
  - voluptuous=0.13.1
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - wrapt=1.15.0
  - xarray=2023.3.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.3
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2023.2.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - yte=1.5.1
  - zc.lockfile=3.0.post1
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - cplex==22.1.1.0
      - docplex==2.25.236
      - gurobipy==10.0.1
      - highspy==1.5.0.dev0
      - pybind11==2.10.4
      - pyomo==6.5.0
