# executor: parallel

meta:
    extract_upstream: False

tasks:
    - name: download_land_sea_mask
      source: scripts.download_land_sea_mask.download_land_sea_mask
      #class: ScriptRunner
      #static_analysis: disable
      product: data/input/land_sea_mask/land_sea_mask.nc

#    - name: generate_renewable_timeseries
#      # note: this task also downloads inputs if necessary
#      source: scripts/generate_renewable_timeseries.py
#      product:
#          era5: data/input/era5/
#          # TODO move this to a separate folder
#          pv: data/interim/pv/pv_2011-*.nc
#          wind: data/interim/wind/wind_2011-*.nc
#
#    - name: concat_renewable_timeseries
#      source: python scripts/concat_renewable_timeseries.py
#      upstream: generate_renewable_timeseries
#      product:
#          pv: data/interim/pv/pv_2011.nc
#          wind: data/interim/wind/wind_2011.nc


    - name: optimize_network-[[chunk[0]]]-[[chunk[1]]]
      source: src.optimize.optimize_network_chunk_ploomber
      upstream:
          #- concat_renewable_timeseries
          - download_land_sea_mask
      product:
          # TODO rename this to chunks
          network_solution: data/interim/network_solution/network_solution_[[chunk[0]]]-[[chunk[1]]].nc
      grid:
          chunk:
              dotted_path: src.util::iter_chunk_indices
              x_idx_from_to: [740, 742]
              y_idx_from_to: [560, 563]
              chunk_size: [1, 1]


#    - name: concat_solution_chunks
#      source: python scripts/concat_solution_chunks.py
#      upstream: optimize_network
#      product:
#          - data/output/network_solution
