# executor: parallel

meta:
    extract_upstream: False

tasks:
    - name: download_land_sea_mask
      source: scripts.download_land_sea_mask.download_land_sea_mask
      #class: ScriptRunner
      #static_analysis: disable
      product: data/input/land_sea_mask/land_sea_mask.nc

#    - name: generate_renewable_timeseries
#      # note: this task also downloads inputs if necessary
#      source: scripts/generate_renewable_timeseries.py
#      product:
#          era5: data/input/era5/
#          # TODO move this to a separate folder
#          pv: data/interim/pv/pv_2011-*.nc
#          wind: data/interim/wind/wind_2011-*.nc
#
#    - name: concat_renewable_timeseries
#      source: python scripts/concat_renewable_timeseries.py
#      upstream: generate_renewable_timeseries
#      product:
#          pv: data/interim/pv/pv_2011.nc
#          wind: data/interim/wind/wind_2011.nc

    - name: optimize_network-[[x_start_idx]]_[[y_start_idx]]
      source: src.optimize.optimize_network_chunk
      upstream:
          #- concat_renewable_timeseries
          - download_land_sea_mask
      product:
          # TODO rename this to chunks
          # FIXME need files
          network_solution: data/interim/network_solution/network_solution_[[x_start_idx]]_[[y_start_idx]].nc
      grid:
          x_start_idx: [740, 745]
          y_start_idx: [560, 565, 570]

#    - name: concat_solution_chunks
#      source: python scripts/concat_solution_chunks.py
#      upstream: optimize_network
#      product:
#          - data/output/network_solution
