# executor: parallel

meta:
    extract_upstream: False

tasks:
    - name: download_land_sea_mask
      source: scripts.download_land_sea_mask.download_land_sea_mask
      #class: ScriptRunner
      #static_analysis: disable
      product: data/input/land_sea_mask/land_sea_mask.nc

#    - name: generate_renewable_timeseries
#      # note: this task also downloads inputs if necessary
#      source: scripts/generate_renewable_timeseries.py
#      product:
#          era5: data/input/era5/
#          # TODO move this to a separate folder
#          pv: data/interim/pv/pv_2011-*.nc
#          wind: data/interim/wind/wind_2011-*.nc
#
#    - name: concat_renewable_timeseries
#      source: python scripts/concat_renewable_timeseries.py
#      upstream: generate_renewable_timeseries
#      product:
#          pv: data/interim/pv/pv_2011.nc
#          wind: data/interim/wind/wind_2011.nc
#
#    - name: optimize_network
#      source: scripts/optimize_network.py
#      upstream:
#          - concat_renewable_timeseries
#          - land_sea_mask
#      product:
#          # TODO rename this to chunks
#          # FIXME need files
#          network_solution: data/interim/network_solution
#      # serializer: src.io.save_textfile
#      # unserializer: src.io.load_textfile
#
#
#    - name: concat_solution_chunks
#      source: python scripts/concat_solution_chunks.py
#      upstream: optimize_network
#      product:
#          - data/output/network_solution
