#
#
#

# 
year_era5: 2011


# values below here are actually global config atm, right?
# do we really need to mengle all params into the file names?

# Balkan
# x_idx_from_to: [750, 840]
# y_idx_from_to: [530, 560]

# Denmark
x_idx_from_to: [740, 800]
y_idx_from_to: [560, 620]

chunk_size: [5, 5]
