#
#
#

# 
year_era5: 2011


# values below here are actually global config atm, right?
# do we really need to mengle all params into the file names?

# Balkan
# x_idx_from_to: [750, 840]
# y_idx_from_to: [530, 560]

# Denmark
x_idx_from_to: [740, 800]
y_idx_from_to: [560, 620]


# how many tiles in x/y are computed in one process at once and then stored in one file
chunk_size: [5, 5]


# resolution of time series for the optimization
time_period_h: "4h"
