# This file contains parameters for the computation. You may want use some of them to put
# additional wildcards in the Sankefile for more sensitivity analysis.


# weather year used for simulation of renewable time series
year_era5: 2011


# Define pixels to be used in the optimization:
# All global pixels: y: 720, x: 1440 (i.e. [0, 1339] and [0, 719])
#
# Balkan
#   x_idx_from_to: [750, 840]
#   y_idx_from_to: [530, 560]
#
# Denmark
#   x_idx_from_to: [740, 800]
#   y_idx_from_to: [560, 620]
#
# Global
#   x_idx_from_to: [0, 1440]
#   y_idx_from_to: [0, 720]

x_idx_from_to: [740, 800]
y_idx_from_to: [560, 620]


# How many pixels in x/y are computed in one process at once and then stored in one file
chunk_size: [5, 5]


# Resolution of time series for the optimization, larger time steps make the optimization way faster
time_period_h: "4h"


# Parameters for PV and wind time series: parameters are passed to the atlite functions
# Cutout.wind() and Cutout.pv(). Each key describes a scenario with a set of parameters for
# renewable time series which is used in the file names.
#
# Note: here are only alphanumeric characters allowed for the key for each scenario. Adapat the
# wildcard_constraints in the Snakefile if you want to use other characters, but - and _ might lead
# to ambiguous rules (AmbiguousRuleException).
#
# https://atlite.readthedocs.io/en/master/ref_api.html#atlite.Cutout.wind
# https://atlite.readthedocs.io/en/master/ref_api.html#atlite.Cutout.pv
renewable_params:
    VestasV903MWCsi30180:
        pv:
            panel: CSi
            orientation:
                slope: 30.0
                azimuth: 180.0
        wind:
            turbine: Vestas_V90_3MW
